### ISSUE TITLE
error with imagenetvitB16 [Solved] 

### ISSUE THREAD

**Issue by wxf12345** [google-research/head2toe#5]
Hello Utku, Thanks for this great research
The evaluate shell with imagenetr50 works well but
when I run the evaluate shell with imagenetvitB16 like
` python -m  head2toe.evaluate --config=head2toe/configs_eval/finetune.py:imagenetvitB16 --config.dataset='data.caltech101' --config.max_num_gpus 1`

I got the TypeError :

```Traceback (most recent call last):
  File "/home/congyu/miniconda3/envs/tensorflow/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/congyu/miniconda3/envs/tensorflow/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/congyu/TextSum/head2toe/head2toe/evaluate.py", line 148, in <module>
    app.run(main)
  File "/home/congyu/miniconda3/envs/tensorflow/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/congyu/miniconda3/envs/tensorflow/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/congyu/TextSum/head2toe/head2toe/evaluate.py", line 71, in main
    model = finetune_fs_models.FinetuneFS(config)
  File "/home/congyu/TextSum/head2toe/head2toe/models/finetune.py", line 118, in __init__
    res = self.load_backbones()
  File "/home/congyu/TextSum/head2toe/head2toe/models/finetune.py", line 145, in load_backbones
    outputs = backbone(resized_inputs)
  File "/home/congyu/miniconda3/envs/tensorflow/lib/python3.7/site-packages/keras/engine/base_layer.py", line 977, in __call__
    input_list)
  File "/home/congyu/miniconda3/envs/tensorflow/lib/python3.7/site-packages/keras/engine/base_layer.py", line 1115, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "/home/congyu/miniconda3/envs/tensorflow/lib/python3.7/site-packages/keras/engine/base_layer.py", line 848, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/congyu/miniconda3/envs/tensorflow/lib/python3.7/site-packages/keras/engine/base_layer.py", line 888, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/congyu/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /home/congyu/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_hub/keras_layer.py:237 call  *
        result = smart_cond.smart_cond(training,
    /home/congyu/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1707 __call__  **
        return self._call_impl(args, kwargs)
    /home/congyu/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1723 _call_impl
        raise structured_err
    /home/congyu/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1717 _call_impl
        cancellation_manager)
    /home/congyu/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1794 _call_with_structured_signature
        self._structured_signature_check_missing_args(args, kwargs)
    /home/congyu/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1815 _structured_signature_check_missing_args
        ", ".join(sorted(missing_arguments))))

    TypeError: signature_wrapper(*, input_1) missing required arguments: input_1```

Is there something wrong in the vit-pipeline or the shell?

**Comment by evcu** [comment]
Will look to this this week; thanks for reporting

**Comment by evcu** [comment]
pip install --upgrade tf-hub-nightly should solve the issue. I also updated the README.md with more details on running experiments. It would be great if you can verify on your end, too.

**Comment by wxf12345** [comment]
Thanks for your suggestion，it works well for me.  I will try these experiments later.
